//Types should be in const to avoid typos and duplication since it's a string and could be easily miss spelled
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const ADD_SHIPPING = 'ADD_SHIPPING';
export const ADD_QUANTITY_WITH_NUMBER = 'ADD_QUANTITY_WITH_NUMBER';
export const ORDER_FORM = 'ORDER_FORM';
export const CHECKOUT_CHARGE = 'CHECKOUT_CHARGE';
export const RESET_CART = 'RESET_CART';
//added by coding

export const CART_ADDED = 'CART_ADDED';
export const CART_COUNT_INIT_SET = 'CART_INIT_SET';
export const SET_CHECKOUT_INFO = 'SET_CHECKOUT_INFO';
export const CLEAR_CHECKOUT_INFO = 'CLEAR_CHECKOUT_INFO';

export const SET_BUYER_INFO_DATA = 'SET_BUYER_INFO_DATA';
export const INIT_BUYER_INFO_DATA = 'INIT_BUYER_INFO_DATA';

// Buyer Info
export const SET_BUYER_INFO_FIRST_NAME = 'SET_BUYER_INFO_FIRST_NAME';
export const SET_BUYER_INFO_LAST_NAME = 'SET_BUYER_INFO_LAST_NAME';
export const SET_BUYER_INFO_COMPANY = 'SET_BUYER_INFO_COMPANY';

export const SET_BUYER_INFO_EMAIL = 'SET_BUYER_INFO_EMAIL';
export const SET_BUYER_INFO_ADDRESS = 'SET_BUYER_INFO_ADDRESS';
export const SET_BUYER_INFO_COUNTRY = 'SET_BUYER_INFO_COUNTRY';
export const SET_BUYER_INFO_STATE = 'SET_BUYER_INFO_STATE';
export const SET_BUYER_INFO_TOWN_CITY = 'SET_BUYER_INFO_TOWN_CITY';
export const SET_BUYER_INFO_PHONE = 'SET_BUYER_INFO_PHONE';
export const SET_BUYER_INFO_ZIP = 'SET_BUYER_INFO_POSTCODE';
export const SET_BUYER_INFO_ORDER_NOTE = 'SET_BUYER_INFO_ORDER_NOTE';


